### ISSUE TITLE
media-library:regenerate doesn't regenerate responsive images

### ISSUE THREAD

**Issue by ctf0** [ctf0/laravel-medialibrary#1]
discuss/track the new feature progress in here.

changes should be applied to https://github.com/ctf0/laravel-medialibrary/tree/patch-3

**Comment by sebapastore** [comment]
Hi @ctf0, when I first check the code in order to understand the causes of the issue, I came into this conclusion:

I think that "media-library:regenerate" is working as espected. In the way I see, the command itself can't just know if the user want or not responsive images to be generated for the base image. It could infer it by inspecting the "responsive_images" field, but I think this wouldn't be an appropiete aproach.

I think it would be better to provide a bool parameter to the command, and based on this, generate or not responsive images for the base image.

**Comment by ctf0** [comment]
yeah i think that too, but actually what the command do is it create missing conversion files, so it must have a way to check if the media item needs a conversion or not, otherwise it will be making it for all of them.

i havent used the conversion b4 so i need to investigate more into how it actually works b4 i plan the next move, because if the command checks each item then there must be a way for it to check for responsive images for each item as well.

plz tell me if you came across any of that or if u have a better plan.

**Comment by sebapastore** [comment]
The command checks it but only for "conversions files" registered on the "registerMediaConversions" function of each model. The problem is for base image.

For conversions there is a specific place to look into in order to know if it's required to generate responsive images:

```<?php
class YourModel extends Model implements HasMedia
{
    use HasMediaTrait;

    /**
     * Register the conversions that should be performed.
     *
     * @return array
     */
    public function registerMediaConversions(Media $media = null)
    {
        $this
            ->addMediaConversion('my-conversion')
            ->withResponsiveImages();
    }
}
```

But if we have generated responsive images for the original image (no for conversions), is because we have something like this somewhere in the code:
```<?php
$model
    ->addMediaFromRequest('image')
    ->withResponsiveImages()
```
So there is not a "specific place" where we can look in order to know if the responsive images are required for the original image.

**Comment by ctf0** [comment]
ok. perfect, its even easier this way, however as we dont need to go through each model i think we should have a new command and make it more performant than the current, or what u think ?

**Comment by sebapastore** [comment]
The problem occurs exactly because ```withResponsiveImages``` can be used outside ```registerMediaCollection```.

I was thinking about when someone would like to use the ```media-library:regenerate``` command.

I think a normal use case is when you make a change in your ```registerMediaCollection```. And another case would be if you add or remove ```withResponsiveImages``` outside ```registerMediaCollection```. Or both cases together.

In any of those cases you would like to regenerate, and I think it would be more intuitive if you can do it with one command. But it's just my point of view.

**Comment by ctf0** [comment]
its ok, we can go with that but there will be a couple of issues

- the current command unless specified, has to go model by model to get all his images and process them, which in our case is redundant.

- because of the prev step, there will be too many db calls which is useless

- creating responsive images already take a lot of time because the images are created based on the original dimension and size, 
so we have to keep in mind those who will generate images on cloud, a new request has to be made for each image to get this details b4 doing any processing.

- a new option will have to be added to the command `--responsive-only` which is already stuffed

**Comment by ctf0** [comment]
@sebapastore r u still into this ?

**Comment by ctf0** [comment]
lets continue on https://github.com/spatie/laravel-medialibrary/pull/2047

**Comment by sebapastore** [comment]
Will look into it next week!
